# ----------------------------
# TIME
# ----------------------------
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# ----------------------------
# CMD_VEL  (ROS -> GZ)
# You have /cmd_vel on ign side, so bridge that.
# ----------------------------
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# ----------------------------
# ODOMETRY (GZ -> ROS)F
# ----------------------------
- ros_topic_name: "/odom"
  gz_topic_name: "/model/my_robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
  
# ----------------------------
# TF (GZ -> ROS)
# ----------------------------
- ros_topic_name: "/tf"
  gz_topic_name: "/model/my_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS


# ----------------------------
# JOINT STATES (GZ -> ROS)
# ----------------------------
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/world_demo/model/my_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# ----------------------------
# LIDAR SCAN (GZ -> ROS)
# ----------------------------
- ros_topic_name: "/scan"
  gz_topic_name: "/robot/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# ----------------------------
# IMU (GZ -> ROS)
# ----------------------------
- ros_topic_name: "/imu"
  gz_topic_name: "/robot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

