teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 5          # R1 usually (change if needed)
    enable_turbo_button: 4    # L1 optional

    axis_linear:
      x: 1                    # Left stick up/down
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 3                  # Left stick left/right
    scale_angular:
      yaw: 1.5
    scale_angular_turbo:
      yaw: 2.0

